# -*- coding: utf-8 -*-
"""IOCL AnamolyDetectionAutomation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HEJfbELMz2jpma12s_v7SYE7u_Nn5Kn8

IOCL Anamoly Detection Automation
"""

# INSTALL & IMPORT LIBRARIES
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import IsolationForest
import smtplib
from email.message import EmailMessage

# UPLOAD DATASET
from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

# Remove duplicates
df.drop_duplicates(inplace=True)

# FEATURE ENGINEERING (SEC)
df["SEC"] = (
    df["electricity_kwh"] +
    df["steam_usage"] +
    df["fuel_usage"]
) / df["production_tons"]

# GLOBAL ANOMALY DETECTION
features = [
    "electricity_kwh",
    "steam_usage",
    "fuel_usage",
    "production_tons",
    "SEC"
]

X = df[features]

global_model = IsolationForest(
    n_estimators=100,
    contamination=0.05,
    random_state=42
)

df["anomaly"] = np.where(global_model.fit_predict(X) == -1, 1, 0)


# GLOBAL ANOMALIES
plt.figure(figsize=(8,5))
plt.scatter(df["production_tons"], df["electricity_kwh"],
            c=df["anomaly"], cmap="coolwarm", s=6)
plt.title("Global Anomaly Detection")
plt.xlabel("Production Tons")
plt.ylabel("Electricity (kWh)")
plt.show()

# UNIT-WISE ANOMALY DETECTION
unit_dfs = {}
unit_models = {}

for unit in df["unit_name"].unique():
    unit_df = df[df["unit_name"] == unit].copy()

    model = IsolationForest(
        n_estimators=100,
        contamination=0.05,
        random_state=42
    )

    unit_df["anomaly"] = np.where(
        model.fit_predict(unit_df[features]) == -1, 1, 0
    )

    unit_dfs[unit] = unit_df
    unit_models[unit] = model

# UNIT-WISE PLOTS
for unit, unit_df in unit_dfs.items():
    plt.figure(figsize=(6,4))
    plt.scatter(
        unit_df["production_tons"],
        unit_df["electricity_kwh"],
        c=unit_df["anomaly"],
        cmap="coolwarm",
        s=6
    )
    plt.title(f"Anomalies in {unit}")
    plt.xlabel("Production Tons")
    plt.ylabel("Electricity (kWh)")
    plt.show()

# SEVERITY CALCULATION
SEC_mean = df["SEC"].mean()

def severity(sec):
    if sec > 1.5 * SEC_mean:
        return "HIGH"
    elif sec > 1.2 * SEC_mean:
        return "MEDIUM"
    else:
        return "LOW"

for unit, unit_df in unit_dfs.items():
    unit_df["severity"] = np.where(
        unit_df["anomaly"] == 1,
        unit_df["SEC"].apply(severity),
        "NORMAL"
    )
    unit_dfs[unit] = unit_df

# SEVERITY DISTRIBUTION
alerts_df = pd.concat(unit_dfs.values())
alerts_df = alerts_df[alerts_df["anomaly"] == 1]

alerts_df["severity"].value_counts().plot(
    kind="bar", title="Alert Severity Distribution"
)
plt.show()

"""SEND AUTOMATED GMAIL ALERT"""

import os
print(os.getcwd())

os.listdir()

# Create alert report again (safe)
alerts_df.to_csv("refinery_alert_report.csv", index=False)

print("File created:", os.path.exists("refinery_alert_report.csv"))

import smtplib
from email.message import EmailMessage

EMAIL = "dharambaba2k4@gmail.com"
APP_PASSWORD = "fugmkuhfxtzeutjm"

msg = EmailMessage()
msg["Subject"] = "🚨 Automated Refinery Energy Anomaly Report"
msg["From"] = EMAIL
msg["To"] = "dharamcodemystery@gmail.com"
msg.set_content("Attached is the automated anomaly alert report.")

with open("refinery_alert_report.csv", "rb") as f:
    msg.add_attachment(
        f.read(),
        maintype="application",
        subtype="octet-stream",
        filename="refinery_alert_report.csv"
    )

with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
    server.login(EMAIL, APP_PASSWORD)
    server.send_message(msg)

print("✅ Automated alert email sent!")

import os

files_to_delete = [
    "refinery_energy_large_dataset (1).csv",
    "refinery_energy_large_dataset (2).csv",
    "refinery_energy_large_dataset (3).csv"
]

for file in files_to_delete:
    path = f"/content/{file}"
    if os.path.exists(path):
        os.remove(path)
        print(f"Deleted: {file}")
    else:
        print(f"Not found: {file}")